name: BoatRacing
main: es.jaie55.boatracing.BoatRacingPlugin
version: ${project.version}
api-version: '1.21'
authors: [Jaie55]
description: An F1‑style ice boat racing plugin for Paper with a clean, vanilla‑like GUI. Manage teams, configure tracks with the built‑in BoatRacing selection tool, run timed races with checkpoints, pit area penalties, and a guided setup wizard.
website: https://modrinth.com/plugin/boatracing
commands:
  boatracing:
    description: BoatRacing base command
    usage: /<command> teams|race|setup|admin|reload|version
    permission: boatracing.use
permissions:
  boatracing.*:
    description: Grant ALL BoatRacing permissions
    default: false
    children:
      boatracing.use: true
      boatracing.teams: true
      boatracing.version: true
      boatracing.reload: true
      boatracing.update: true
      boatracing.setup: true
      boatracing.admin: true
      boatracing.race.join: true
      boatracing.race.leave: true
      boatracing.race.status: true
      boatracing.race.admin: true
  boatracing.use:
    description: Meta permission for BoatRacing base usage
    default: true
    children:
      boatracing.teams: true
      boatracing.version: true
      boatracing.race.join: true
      boatracing.race.leave: true
      boatracing.race.status: true
  boatracing.teams:
    description: Use /boatracing teams
    default: true
  boatracing.version:
    description: Use /boatracing version
    default: true
  boatracing.reload:
    description: Reload BoatRacing plugin configuration and data
    default: op
  boatracing.update:
    description: Receive in-game update notifications
    default: op
  boatracing.setup:
    description: Configure tracks and regions (admins)
    default: op
  boatracing.admin:
    description: Administer teams and players (create/rename teams, assign members, set numbers/boats)
    default: op
    children:
      boatracing.use: true
      boatracing.teams: true
      boatracing.version: true
      boatracing.reload: true
      boatracing.update: true
      boatracing.setup: true
      boatracing.race.join: true
      boatracing.race.leave: true
      boatracing.race.status: true
      boatracing.race.admin: true
  boatracing.race.join:
    description: Join a race registration
    default: true
  boatracing.race.leave:
    description: Leave a race registration
    default: true
  boatracing.race.status:
    description: View race status for a track
    default: true
  boatracing.race.admin:
    description: Manage races (open/start/force/stop)
    default: op
