name: BoatRacing
main: es.jaie55.boatracing.BoatRacingPlugin
version: 1.0.0
api-version: '1.21'
authors: [Jaie55]
description: F1-style ice boat racing plugin
commands:
  boatracing:
    description: BoatRacing base command
    usage: /<command> teams|reload|version
permissions:
  boatracing.use:
    description: Meta permission for BoatRacing base usage
    default: true
    children:
      boatracing.teams: true
      boatracing.version: true
  boatracing.teams:
    description: Use /boatracing teams
    default: true
  boatracing.version:
    description: Use /boatracing version
    default: true
  boatracing.reload:
    description: Reload BoatRacing plugin configuration and data
    default: op
  boatracing.update:
    description: Receive in-game update notifications
    default: op
